### ISSUE TITLE
Error no Backup.

### ISSUE THREAD

**Issue by domflamingo2** [eduardo-mior/System#11]
Olá Eu refiz seu plugin todo pra testa bugs,, mas aconteceu alguns erros que não era pra acontecer pois eu segui seu metado, mas caso ainda trabalha no plugin, seria bom resolver ate agora não consegui '-'.

obs: não alterei nada na utils/Backup so dei control c e control v.

```java
[09:56:51] [Server thread/INFO]: Deividgab issued server command: /backup
[09:56:55] [Server thread/INFO]: Deividgab issued server command: /essentials backup
[09:56:55] [Thread-11/WARN]: java.io.FileNotFoundException: H:\Coisas\1.8\plugins\System\backups\Dia 28-12-2020 Hora09;56.zip (O sistema não pode encontrar o caminho especificado)
[09:56:55] [Thread-11/WARN]: 	at java.io.FileOutputStream.open0(Native Method)
[09:56:55] [Thread-11/WARN]: 	at java.io.FileOutputStream.open(Unknown Source)
[09:56:55] [Thread-11/WARN]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[09:56:55] [Thread-11/WARN]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[09:56:55] [Thread-11/WARN]: 	at System.utils.Backup.zipFolder(Backup.java:31)
[09:56:55] [Thread-11/WARN]: 	at System.utils.Backup.create(Backup.java:24)
[09:56:55] [Thread-11/WARN]: 	at System.comandos.ComandoSystem.lambda$onCommand$0(ComandoSystem.java:58)
[09:56:55] [Thread-11/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by eduardo-mior** [comment]
Não sei oque pode ter acontecido nesse seu caso, pelo que entendi você tentou usar o comando /system backup mas não funcionou.
Você poderia me explicar qual o passo a passo você fez para reproduzir o erro? Aqui eu testei e funcionou perfeitamente.
