### ISSUE TITLE
Error no Playerdate

### ISSUE THREAD

**Issue by domflamingo2** [eduardo-mior/System#12]
```java
[09:55:59] [User Authenticator #1/INFO]: UUID of player Deividgab is ***censurado***
[09:55:59] [Server thread/INFO]: [0;31;1m[ERROR] O arquivo não pôde ser criado deividgab.yml![m
[09:55:59] [Server thread/WARN]: java.io.IOException: O sistema não pode encontrar o caminho especificado
[09:55:59] [Server thread/WARN]: 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[09:55:59] [Server thread/WARN]: 	at java.io.File.createNewFile(Unknown Source)
[09:55:59] [Server thread/WARN]: 	at System.utils.manager.DataManager.createFile(DataManager.java:22)
[09:55:59] [Server thread/WARN]: 	at System.sistemas.gerais.PlayerData.newPlayer(playerdate.java:28) -> DataManager.createFile(file);
[09:55:59] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:55:59] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:55:59] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:55:59] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:55:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[09:55:59] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[09:55:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[09:55:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.attemptLogin(PlayerList.java:456)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:118)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[09:55:59] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[09:55:59] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by uRyanxD** [comment]
Sò contigo que dá esses erro k

**Comment by eduardo-mior** [comment]
Qual o passo a passo você fez para reproduzir este erro?
Se não me engano eu já vi esse erro acontecer quando você entra no servidor e apaga a pasta do system com o servidor ligado. Ou quando você apaga a pasta do system como o servidor ligado e tenta entrar no servidor.
Sem mais informações e o passo a passo pra mim reproduzir fica difícil.
