### ISSUE TITLE
error 1.19.2 purpur

### ISSUE THREAD

**Issue by OneHitX** [eduardo-mior/System#21]
[23:50:05 ERROR]: Could not pass event PrepareItemCraftEvent to System v1.14.19
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.Material.getId(Material.java:4194) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at rush.recursos.bloqueadores.BloquearCrafts.aoPrepararCraft(BloquearCrafts.java:19) ~[System.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1770]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1391) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:87) ~[?:?]
        at net.minecraft.world.inventory.CraftingMenu.lambda$slotsChanged$0(CraftingMenu.java:98) ~[?:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:67) ~[?:?]
        at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:54) ~[?:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:66) ~[?:?]
        at net.minecraft.world.inventory.CraftingMenu.slotsChanged(CraftingMenu.java:97) ~[?:?]
        at net.minecraft.world.inventory.CraftingContainer.removeItem(CraftingContainer.java:132) ~[?:?]
        at net.minecraft.world.inventory.ResultSlot.onTake(ResultSlot.java:67) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.lambda$doClick$3(AbstractContainerMenu.java:564) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:562) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:381) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3410) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1770]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by eduardo-mior** [comment]
@OneHitX esse erro só acontece com a JAR do Purpur ou acontece com outras JAR da 1.19 também?

**Comment by eduardo-mior** [comment]
@OneHitX se você não utiliza a funcionalidade de "BloquearCrafts" você pode desabilitar na Config que ele vai parar de dar esse erro, mas se possível verifica pra mim por favor se esse problema só acontece com a JAR do PurPur ou acontece com a Jar do Spigot e do Paper também

**Comment by OneHitX** [comment]
Acontece com paper/spigot ou qualquer versão desde que seja a 1.19.2
@eduardo-mior

**Comment by eduardo-mior** [comment]
@OneHitX você utiliza a função BloquearCrafts? Se você não utilizada essa função pode desabilitar que vai parar de dar o erro.
