### ISSUE TITLE
Erro PlayerKickEvent 1.19.2 purpur

### ISSUE THREAD

**Issue by ghost** [eduardo-mior/System#22]
23:40:54 ERROR]: Could not pass event PlayerKickEvent to System v1.14.18
java.lang.NullPointerException: Cannot invoke "String.length()" because "input" is null
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:242) ~[adventure-text-serializer-legacy-4.11.0.jar:?]
        at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:134) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at rush.recursos.desativadores.DesativarMensagemDeSaida.aoSerKickado(DesativarMensagemDeSaida.java:18) ~[System.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor318.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1777]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:554) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:519) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:2169) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1777]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

**Comment by eduardo-mior** [comment]
Algum plugin que você esta usando esta tentando pegar o tamanho da mensagem que é exibida quando um jogador é kikado do servidor, porém o system desativa a mensagem de jogador kikado/expulso do servidor.

Oque você pode fazer para corrigir esse problema é ir no settings.yml do System e desativar a config "desativar-mensagem-de-saida", isso vai fazer parar de dar erro.

O plugin que esta dando problema e o net.kyori.adventure. Se não me engano já teve outra pessoa que reportou esse problema antes, mas não é problema do System na real.

**Comment by uRyanxD** [comment]
net.kyori.adventure é uma depêndencia do Paper (Purpur é fork do Paper)

**Comment by eduardo-mior** [comment]
@uRyanxD então pode ser que esse erro só aconteça no Paper e no Pupur, no Spigot e no Bukkit não deve acontecer.

Vou analisar para corrigir quando for possível.
