### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to System v1.14.18

### ISSUE THREAD

**Issue by Niix-Dan** [eduardo-mior/System#23]
- [Sat 22:27:27 ERROR Minecraft] Could not pass event PrepareItemCraftEvent to System v1.14.18
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593)
    at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1234)
    at net.minecraft.inventory.container.WorkbenchContainer.func_217066_a(WorkbenchContainer.java:89)
    at net.minecraft.inventory.container.WorkbenchContainer.a(WorkbenchContainer.java:100)
    at net.minecraft.inventory.container.PlayerContainer.func_75130_a(PlayerContainer.java:114)
    at net.minecraft.inventory.CraftingInventory.func_70298_a(CraftingInventory.java:120)
    at net.minecraft.inventory.container.CraftingResultSlot.func_190901_a(CraftingResultSlot.java:65)
    at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:430)
    at net.minecraft.inventory.container.Container.func_184996_a(Container.java:230)
    at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2326)
    at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34)
    at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12)
    at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
    at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
    at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
    at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
    at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:939)

**Comment by eduardo-mior** [comment]
@Niix-Dan poderia me mandar foto do /system info e do /system debug? e poderia me mandar a log completa por favor...

Provavelmente esse erro é por conta do BloquearCrafts que não funciona mais nessas versões mais recentes do minecraft

**Comment by Brasil150** [comment]
Olá @eduardo-mior estou recebendo esse erro também na 1.19.4. Sabe o que causa isso?

[00:06:17] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to System v1.14.18
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.Material.getId(Material.java:4644) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at rush.recursos.bloqueadores.BloquearCrafts.aoPrepararCraft(BloquearCrafts.java:19) ~[System (2).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor251.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1957]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1408) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:91) ~[?:?]
	at net.minecraft.world.inventory.InventoryMenu.slotsChanged(InventoryMenu.java:164) ~[?:?]
	at net.minecraft.world.inventory.CraftingContainer.removeItem(CraftingContainer.java:132) ~[?:?]
	at net.minecraft.world.inventory.ResultSlot.onTake(ResultSlot.java:67) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.lambda$doClick$3(AbstractContainerMenu.java:566) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:564) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:383) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3293) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by eduardo-mior** [comment]
@Brasil150 provavelmente é por conta do recurso BloquearCrafts, que não deve mais funcionar nas versões mais recentes do minecraft, por conta disso deve ser desativado no arquivo settings.yaml

**Comment by Brasil150** [comment]
Tá certo, vou verificar se resolve!
[image](https://github.com/eduardo-mior/System/assets/55663598/7a53ce1d-13c3-4b5f-a70f-78fa8dadc34d)
